# trigger deploy
[phases.setup]
nixPkgs = ["php84", "php84Extensions.pdo_mysql", "php84Extensions.mbstring", "php84Extensions.openssl", "php84Extensions.gd", "composer", "nodejs"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader", "npm install && npm run build"]

[start]
cmd = "php artisan config:cache && php artisan route:cache && php -S 0.0.0.0:$PORT -t public"
